### ISSUE TITLE
Dynamic libraries aren't found at runtime

### ISSUE THREAD

**Issue by UncannyBingo** [lasote/conan-gtest-example#1]
Building this example works great on my system (OS X 10.11.3, make 3.4.3), but running the resulting builds fail with the following error:
`$ ./bin/encryption_test 
dyld: Library not loaded: libssl.1.0.0.dylib
  Referenced from: [redacted]./bin/encryption_test
  Reason: image not found
Trace/BPT trap: 5`

Switching to static libraries works :)

**Comment by lasote** [comment]
Hi! Its working fine for me. Do you have the "libssl.1.0.0.dylib" file in your "bin" folder together with the encryption_test?

**Comment by UncannyBingo** [comment]
Aha, now I see the problem, thanks to your prompting. I am doing an out-of-directory build. All of the `dylibs` are in `projects/conan-gtest-example/bin/`, but the build is happening in `projects/conan-gtest-example-build`, which is where the executable winds up.

So the problem is almost certainly: This example doesn't support out-of-directory builds. Actually, looking at `conanfile.txt`, the problem might be that _Conan_ doesn't really support out-of-directory builds?

**Comment by DEGoodmanWilson** [comment]
Yes, on reflection, it would be strongly preferable if Conan didn't put retrieved binaries in the source folder, but in the folder in which cmake was invoked.

**Comment by lasote** [comment]
Yes, should be fine. Try to change the conanfile.txt [imports] section. It define the folder where the dynlibs are copied. If I get some time I will try it.

**Comment by UncannyBingo** [comment]
Found these, and this helps some of the issues I've been having in understanding out to do out-of-source builds:
http://docs.conan.io/en/latest/manage_deps/workflows.html

Re: your suggestion: it won't always be known in advance where to put the dylibs, for example, when using CLion, or with multiple build configurations. I worry that the problem is perhaps more general? Perhaps I am missing something, however.

Thanks for taking the time to answer my questions, BTW!

**Comment by lasote** [comment]
Great! I saw your luna repository and the conanfile.py.
That's the right way to use all the conan's power ;)
Any other doubt about conan you can open an issue in conan repository.
